name: frkthreads
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  intl: ^0.20.2
  flutter_image_compress: ^2.4.0
  geolocator: ^14.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.0
  google_maps_flutter: ^2.12.1 # Ensure this is included
  shimmer: ^3.0.0
  google_generative_ai: ^0.4.7
  animated_text_kit: ^4.2.3
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  curved_navigation_bar: ^1.0.6
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  cached_network_image: ^3.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
