// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl1qcQLENHlcR-rYMuO7jSxlpDuOWvO8M',
    appId: '1:133593271209:web:80f2168217f6cfce0652b8',
    messagingSenderId: '133593271209',
    projectId: 'frkthreads',
    authDomain: 'frkthreads.firebaseapp.com',
    storageBucket: 'frkthreads.firebasestorage.app',
    measurementId: 'G-JCKR05J8B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDerDfFkPY9du78coXjvekEGXuG314pZTw',
    appId: '1:133593271209:android:6f0944846a758c2f0652b8',
    messagingSenderId: '133593271209',
    projectId: 'frkthreads',
    storageBucket: 'frkthreads.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVqSIaOiXP8DYSxdKxR-D7nL0s6fx6T_4',
    appId: '1:133593271209:ios:63d53d1e84650a1b0652b8',
    messagingSenderId: '133593271209',
    projectId: 'frkthreads',
    storageBucket: 'frkthreads.firebasestorage.app',
    iosBundleId: 'com.example.frkthreads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVqSIaOiXP8DYSxdKxR-D7nL0s6fx6T_4',
    appId: '1:133593271209:ios:63d53d1e84650a1b0652b8',
    messagingSenderId: '133593271209',
    projectId: 'frkthreads',
    storageBucket: 'frkthreads.firebasestorage.app',
    iosBundleId: 'com.example.frkthreads',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl1qcQLENHlcR-rYMuO7jSxlpDuOWvO8M',
    appId: '1:133593271209:web:8c6472d206e150480652b8',
    messagingSenderId: '133593271209',
    projectId: 'frkthreads',
    authDomain: 'frkthreads.firebaseapp.com',
    storageBucket: 'frkthreads.firebasestorage.app',
    measurementId: 'G-YM28ME9KXD',
  );
}
